
---
on:
  push:
    branches:
      - probably-not-needed-see-todo-below
  workflow_call:
    inputs: {}
  workflow_dispatch:
    inputs: {}

jobs:
  mklibs:
    env:
      GITHUB_TOKEN: ${{ github.token }}
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            kernel: linux
        arch:
          - go_name: amd64
            gcc_name: x64

    runs-on: ${{ matrix.platform.os }}

    steps:
      - name: set up gcc
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: ${{ matrix.arch.gcc_name }}
      - run: which gcc
      - run: gcc --version

      - name: check out ${{ github.repository }}
        uses: actions/checkout@v3

      - name: check out the actual pcre2 library
        uses: actions/checkout@v3
        with:
          repository: PCRE2Project/pcre2
          path: pcre2
          ref: pcre2-10.42

      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20'

      - name: install ccgo
        run: go install modernc.org/ccgo/v3@latest
      - run: ccgo -version

      - name: clean and (re)configure pcre2
        run: cd pcre2 && git reset --hard && git clean -dfx && ./autogen.sh && ./configure --disable-shared && ccgo -compiledb ../pcre.json make

      - name: build pcre2_${{ matrix.platform.kernel }}_${{ matrix.arch.go_name }}.go
        run: >
          CC=$(which gcc) ccgo -o pcre2_${{ matrix.platform.kernel }}_${{ matrix.arch.go_name }}.go -pkgname lib
          -trace-translation-units -export-externs X -export-defines D -export-fields F -export-structs S
          -export-typedefs T pcre.json .libs/libpcre2-8.a

      # TODO: 
      # - copy the new capi_*.go and pcre2_*.go into lib/

      # TODO:
      # - add a commit with the new libs

      # NOTE: probably, none of this is necessary at all. mostly I've only
      # really chagned the pcre.go and I don't think changes to it in any way
      # need to be recompiled into lib/
